Update jenkinsfile

diff --git a/jenkinsfile b/jenkinsfile
--- a/jenkinsfile
+++ b/jenkinsfile
@@ -22,7 +22,9 @@ pipeline {
             steps {
                 script {
                     echo "Building Docker image ${imageName}..."
-                    bat "docker build -t ${imageName} . || echo 'Docker build failed.'"
+                    bat """
+                    docker build -t ${imageName} . || echo 'Docker build failed.'
+                    """
                 }
             }
         }
@@ -30,13 +32,14 @@ pipeline {
             steps {
                 script {
                     echo "Stopping and removing existing container ${containerName} if it exists..."
-                    bat '''
-                    docker ps -q --filter name=${containerName} | findstr . && docker stop ${containerName} || echo No running container to stop
-                    docker ps -a -q --filter name=${containerName} | findstr . && docker rm ${containerName} || echo No container to remove
-                    '''
+                    bat """
+                    docker ps -q --filter name=${containerName} | findstr . && docker stop ${containerName} || echo 'No running container to stop'
+                    docker ps -a -q --filter name=${containerName} | findstr . && docker rm ${containerName} || echo 'No container to remove'
+                    """
                     echo "Deploying Docker container ${containerName}..."
-                    echo "Running command: docker run -d --name ${containerName} -p 80:80 ${imageName}"
-                    bat "docker run -d --name ${containerName} -p 80:80 ${imageName} || echo 'Docker run failed.'"
+                    bat """
+                    docker run -d --name ${containerName} -p 80:80 ${imageName} || echo 'Docker run failed.'
+                    """
                 }
             }
         }
