Update jenkinsfile

diff --git a/jenkinsfile b/jenkinsfile
--- a/jenkinsfile
+++ b/jenkinsfile
@@ -3,6 +3,7 @@ pipeline {
 
     environment {
         imageName = 'newswebsite:latest' // Define the image name here
+        containerName = 'newswebsite_container' // Define the container name to use
     }
 
     stages {
@@ -28,14 +29,14 @@ pipeline {
         stage('Deploy Docker Container') {
             steps {
                 script {
-                    echo 'Stopping and removing existing container newswebsite_container if it exists...'
+                    echo "Stopping and removing existing container ${containerName} if it exists..."
                     bat '''
-                    docker ps -q --filter name=newswebsite_container | findstr . && docker stop newswebsite_container || echo No running container to stop
-                    docker ps -a -q --filter name=newswebsite_container | findstr . && docker rm newswebsite_container || echo No container to remove
+                    docker ps -q --filter name=${containerName} | findstr . && docker stop ${containerName} || echo No running container to stop
+                    docker ps -a -q --filter name=${containerName} | findstr . && docker rm ${containerName} || echo No container to remove
                     '''
-                    echo "Deploying Docker container newswebsite_container..."
-                    echo "Running command: docker run -d --name newswebsite_container -p 80:80 ${imageName}"
-                    bat "docker run -d --name newswebsite_container -p 80:80 ${imageName} || echo 'Docker run failed.'"
+                    echo "Deploying Docker container ${containerName}..."
+                    echo "Running command: docker run -d --name ${containerName} -p 80:80 ${imageName}"
+                    bat "docker run -d --name ${containerName} -p 80:80 ${imageName} || echo 'Docker run failed.'"
                 }
             }
         }
